# Generated by Django 5.1.5 on 2025-02-08 15:28

import uuid
import users.utils.helper
from django.db import migrations, models

def generate_unique_tokens(apps, schema_editor):
    CustomUser = apps.get_model("users", "CustomUser")

    for user in CustomUser.objects.all():
        user.email_verification_token = uuid.uuid4()
        user.save()
        
class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_verification_token',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.RunPython(generate_unique_tokens),
        migrations.AlterField(
            model_name="customuser",
            name="email_verification_token",
            field=models.UUIDField(unique=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default_avatar.jpg', null=True, upload_to=users.utils.helper.user_avatar_upload_path),
        ),
    ]
